language: node_js
node_js:
  - "8"
branches:
  only:
    - master
install:
  - npm install
script:
  - npx npm run build

notifications:
  slack: 
    rooms:
      - whizjs:1Yj4kddwBKy8c4CRFLdZFrf3#superjs
    on_success: always
    on_failure: always