language: node_js
node_js:
  - "8"
sudo: required
branches:
  only:
    - master
install:
  - sudo yarn install
script:
  - sudo yarn build

notifications:
  slack: 
    rooms:
      - whizjs:1Yj4kddwBKy8c4CRFLdZFrf3#superjs
    on_success: always
    on_failure: always