[build]
  # Default build command.
  command = "yarn build"

  # Directory with the lambda functions to deploy to AWS.
  functions = "lambda"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://superjs.netlify.com/*"
  to = "https://superjs.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false